### ISSUE TITLE
Failed to Load Data

### ISSUE THREAD

**Issue by Zino301** [idolize/xcloud-keyboard-mouse#7]
The extension doesnt work for me at the moment. When I click on the extension is just says "Failed to load data" See attached screenshot for reference. I've tried refreshing when the game is loading but it doesnt enable and just gives me that error message. 

I am on a VPN, could that be the reason? I'm in the US but the VPN connects to another state within the US
![Screen Shot 2021-11-30 at 10 20 14 AM](https://user-images.githubusercontent.com/95302986/144086387-3c8dd2c2-dd85-4a61-8872-eff2f3bde282.png)

**Comment by idolize** [comment]
@Zino301 thanks for posting - that should only happen if it can't access t[he Chrome built-in "sync" storage](https://developer.chrome.com/docs/extensions/reference/storage/), where your presets are stored and updated.

This should be a built-in feature of Chrome, but maybe you have it disabled? https://support.google.com/chrome/answer/185277?hl=en&co=GENIE.Platform%3DDesktop

If so, I can probably fall back more gracefully to offline-only storage, but this will just mean if you switch to a new computer none of your settings or presets will be available.

**Comment by xsythe** [comment]
Hi there - I'm experiencing the same issue! :(

**Comment by mainarleao** [comment]
I also have the same error, my account is logged in and the sync is active

**Comment by amkamdar** [comment]
same -- tried removing / re-adding the ext but no luck

**Comment by idolize** [comment]
Thanks everyone - this is very interesting. I'm uploading a new version of the extension which will provide more details when this error occurs, so once that version goes live (version `2.0`) it'd be great if you could try again and post the details here, because I have not been able to trigger this issue myself.

**Comment by mainarleao** [comment]
error:

Unable to access settings from storage

Error: "Cannot read property 'ACTIVE_GP_CONF' of undefined"

Please post this issue to GitHub

**Comment by idolize** [comment]
@mainarleao Thank you! This is very helpful. Looks like the `chrome.storage.sync.get` returns `undefined` for some reason (the docs say it should return an object).

I've added a guard against this here: https://github.com/idolize/xcloud-keyboard-mouse/commit/ea9a981537f244a82ca0ab4c6e94fdc17eb083e1 which should hopefully resolve the issue for you.

I'm making a new release currently and will submit to the Chrome Web Store (and MS Edge store) right away as soon as it's done (version 2.2). It may take a few hours (or as long as a day) before it is resolved in the store.

**Comment by amkamdar** [comment]
awesome! thanks :)

**Comment by idolize** [comment]
@amkamdar @mainarleao Looks like `2.2` is live now! https://chrome.google.com/webstore/detail/keyboard-mouse-for-xbox-x/nmfedkijhhigaikbadoijiolmjjgoimd

**Comment by amkamdar** [comment]
Finally got it to load!! So that part is working -- but still not able to play. Went to test the preset and it's still showing as no gamepad detected.

**Comment by amkamdar** [comment]
![image](https://user-images.githubusercontent.com/40646907/144474170-e65b0269-08f5-4df9-997f-1726e28f203e.png)

**Comment by idolize** [comment]
@amkamdar wow, strange. Have you tried reinstalling the extension and refreshing the gamepad-tester.com page?

I may need to add some kind of debug/logging into the extension to get more information as to what is going wrong. Sorry for the troubles - we will get it figured out eventually.

**Comment by amkamdar** [comment]
tried that, no luck. No worries at all! I never use microsoft edge but tried the extension on that and it works perfectly !

**Comment by idolize** [comment]
Closing this issue because it sounds like it is resolved. Feel free to open a new issue or reply here if not! :)
